### PR TITLE
Add the packaging metadata to build the tezos snap

### PR DESCRIPTION
**Pull request by come-maiz**
This package will let you publish the latest tezos in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by come-maiz** [comment]
Hello good people of tezos!

Here in Ubuntu we are writing a new packaging system, that will let upstream control their packages directly and push them to the store following their own development cycle. I would love to see tezos in the store and I had to test a few new features that we are about to release, so I took the opportunity to try making a snap with ocaml.

It has been quite a trip. This is a very interesting use case for us, because you require a lot of packages with newer versions than the ones in Ubuntu 16.04. So, making a snap that will work for the millions of users in that release would be very nice. But things become more complicated with the package, because now many things have to be installed from upstream or other package managers instead of the Ubuntu archive.

I have solved most of the problems I found to compile tezos. But there's one remaining that I don't understand:

    ocamlfind: Package `mtime.os' not found

Do you know how to solve that?

If you want to give this a try, in Ubuntu 16.04:

    $ sudo apt install git snapcraft
    $ git clone https://github.com/elopio/tezos
    $ cd tezos
    $ git checkout snapcraft
    $ snapcraft

You can read more about snaps here: https://snapcraft.io

**Comment by come-maiz** [comment]
I forgot to mention what will seem obvious when you look at the build metadata. This is my first real approach to ocaml. I'm sure I'm doing a lot of things more complicated than I should. Any suggestions to improve the packaging will be very appreciated.

pura vida.

**Comment by samoht** [comment]
```
ocamlfind: Package `mtime.os' not found
```

means that you need a version of `mtime` < 1.0.0

**Comment by come-maiz** [comment]
Thanks @samoht! I found that i can pin a particular version, and I did that for mtime and irmin. Now I'm getting:
```
bisect_ppx, calendar, cohttp, conduit, conf-libev, git, git-unix,
ipv6-multicast, irmin-watcher, js_of_ocaml, kaputt, leveldb, lwt_ssl,
magic-mime, menhir, ocp-ocamlres, ocplib-resto, reactiveData, sodium and
tyxml are not installed. Install them ? [Y/n] y
The following dependencies couldn't be met:
  - irmin → ezjsonm < 0.5.0 → sexplib < 113.01.00 →
    ocaml < 4.03.0 → ocaml-variants < 4.02.4~
    conflict with the base packages of this switch
  - irmin → ezjsonm < 0.5.0 → sexplib < 113.01.00 →
    ocaml < 4.03.0 → ocaml-system < 4.03.0
    unmet availability conditions, e.g. sys-ocaml-version = "4.02.3"
  - irmin → ezjsonm < 0.5.0 → sexplib < 113.01.00 →
    ocaml < 4.03.0 → ocaml-base-compiler < 4.03.0
   conflict with the base packages of this switch
  - irmin → ezjsonm < 0.5.0 → ocaml < 4.03.0 →
    ocaml-base-compiler < 4.03.0
    conflict with the base packages of this switch
  - irmin → ezjsonm < 0.5.0 → ocaml < 4.03.0 →
    ocaml-system < 4.03.0
    unmet availability conditions, e.g. sys-ocaml-version = "4.02.3"
  - irmin → ezjsonm < 0.5.0 → ocaml < 4.03.0 →
    ocaml-variants < 4.02.4~
    conflict with the base packages of this switch
Your request can't be satisfied:
  - No available version of ezjsonm satisfies the constraints
```
I wonder if I'm getting myself in a mess that could be solved in a very simple way. :/

**Comment by samoht** [comment]
Probably wrong version of the OCaml compiler. Not sure what is the recommended one to build tezos, but the install scripts just seem to pin some packages to their dev version: https://github.com/tezos/tezos/blob/master/scripts/install_build_deps.sh#L47 (note: I have no idea how to build tezos, so do not take my advices as the right thing to do ;-) )

**Comment by come-maiz** [comment]
I chose 4.04.0 because the readme says:

    opam switch tezos --alias-of 4.04.0

So maybe let's wait for somebody from tezos to comment.

@samoht I appreciate your help a lot anyway. And I have interest in making more ocaml snaps for the Ubuntu store, and maybe in the future a snapcraft plugin. irmin might be a good candidate. If you have any ideas, suggestions or want to help, please let me know!

pura vida.

**Comment by come-maiz** [comment]
@tezos :thinking: just closed? A comment with a reason would be nice.

**Pull request closed without merging**
