### PR TITLE
list_rev_sub O(sublist length) instead of O(list length)

### PR DESCRIPTION
**Pull request by coventry**
Using fold_left here iterates over the entire list, whereas you only need to
iterate over the first n elements.

### CODE REVIEW

**Comment by ghost** [comment]
It is broken for `n=0`.

**Comment by coventry** [comment]
Thanks. I pushed a change which fixes that, but I'll push some tests too in a few hours.

**Comment by coventry** [comment]
@OCamlPro-Henry, can you please take another look?

**Comment by coventry** [comment]
Happy to remove the test if necessary. Probably redundant.

**Comment by ghost** [comment]
Merged without the test and with `invalid_arg` instead of `failwith`.

**Comment by ghost** [comment]
Thanks!

**Pull request closed without merging**
